# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: frappy writer
email: your-email@example.com
description: >- 
  My name is Mathew. I like to write for fun. I hope you enjoy the things that come out of my mind :)
baseurl: "/Frappy-Blog" # the subpath of your site, e.g. /blog
url: "https://mkowusujr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mkowusujr
  
# Build settings
include: ['_pages']
sass:
  style: compressed
  sass_dir: _sass
plugins:
  - jekyll-feed
